/-
Copyright (c) 2026 Vincent Quenneville-Belair. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vincent Quenneville-Belair
-/
module

public import TauCeti.GroupTheory.Perm.Certificates.Soundness
public import TauCeti.GroupTheory.Perm.WordsAndCycles

/-!
# An executable classical certificate checker

Every decidable quantifier below ranges over points or generator indices.
Primitivity and the single-cycle property are checked by finite saturation.
The validity theorem connects these computations to the classical soundness
theorem. An accepted value carries the checked certificate and its proof.
-/

open Equiv Equiv.Perm

@[expose] public section

namespace TauCeti.CertifiedPermutation

deriving instance DecidableEq, Repr for Claim

variable {α : Type*} [Fintype α] [DecidableEq α]

/-- Finite pointwise, cardinality, and orbit conditions of a decoded certificate. -/
def finiteBaseChecks {P : Subgroup (Perm α)} (c : DecodedCertificate P) : Prop :=
  c.fixedSet.Nonempty ∧ c.fixedSet.card + 1 < Fintype.card α ∧
    c.base ∉ c.fixedSet ∧
    (∀ i : Fin c.generators.length, ∀ x ∈ c.fixedSet,
      (c.generators.get i : Perm α) x = x) ∧
    ∀ x ∉ c.fixedSet, (signedWordEval c.generators (c.orbitWords x) : Perm α) c.base = x

/-- The base-certificate predicates can be checked by finite enumeration. -/
instance {P : Subgroup (Perm α)} (c : DecodedCertificate P) :
    Decidable (finiteBaseChecks c) :=
  inferInstanceAs (Decidable (_ ∧ _ ∧ _ ∧ _ ∧ _))

/-- Check primitivity and the finite base-certificate conditions. -/
def baseCheck (gs : List (Perm α)) (c : DecodedCertificate (FiniteAction.ambientGroup gs)) :
    Bool :=
  FiniteAction.primitiveCheck gs c.base && decide (finiteBaseChecks c)

theorem baseCheck_iff (gs : List (Perm α))
    (c : DecodedCertificate (FiniteAction.ambientGroup gs)) :
    baseCheck gs c = true ↔ BaseValid c := by
  rw [baseCheck, Bool.and_eq_true, FiniteAction.primitiveCheck_iff]
  have hchecks : decide (finiteBaseChecks c) = true ↔ finiteBaseChecks c :=
    ⟨of_decide_eq_true, fun h => decide_eq_true h⟩
  rw [hchecks]
  change (MulAction.IsPreprimitive (FiniteAction.ambientGroup gs) α ∧
    c.fixedSet.Nonempty ∧ c.fixedSet.card + 1 < Fintype.card α ∧
    c.base ∉ c.fixedSet ∧
    (∀ i : Fin c.generators.length, ∀ x ∈ c.fixedSet,
      (c.generators.get i : Perm α) x = x) ∧
    ∀ x ∉ c.fixedSet, (signedWordEval c.generators (c.orbitWords x) : Perm α) c.base = x) ↔ _
  constructor
  · rintro ⟨hp, hs, hn, hb, hf, hw⟩
    exact ⟨hp, hs, by simpa [Nat.card_eq_fintype_card] using hn, hb,
      List.forall_mem_iff_get.mpr hf, hw⟩
  · intro h
    exact ⟨h.primitive, h.fixedNonempty,
      by simpa [Nat.card_eq_fintype_card] using h.cardinality, h.baseOutside,
      List.forall_mem_iff_get.mp h.fixes, h.reaches⟩

/-- Check that the supplied conjugate product is a prime cycle of permitted length. -/
def cycleValidCheck {P : Subgroup (Perm α)} (c : DecodedCertificate P) : Bool :=
  FinitePermutation.cycleCheck (cycleValue c) &&
    decide ((cycleValue c).support.card.Prime ∧
      (cycleValue c).support.card + 3 ≤ Fintype.card α)

theorem cycleValidCheck_iff {P : Subgroup (Perm α)} (c : DecodedCertificate P) :
    cycleValidCheck c = true ↔ CycleValid c := by
  simp [cycleValidCheck, FinitePermutation.cycleCheck_iff, CycleValid,
    Nat.card_eq_fintype_card]

/-- Check the parity and cycle conditions required by the requested claim. -/
def claimCheck {P : Subgroup (Perm α)} (c : DecodedCertificate P) : Bool :=
  match c.claim with
  | .doublyTransitive => true
  | .alternating =>
      cycleValidCheck c &&
        decide (∀ i : Fin c.generators.length, sign (c.generators.get i : Perm α) = 1)
  | .symmetric =>
      cycleValidCheck c &&
        decide (∃ i : Fin c.generators.length, sign (c.generators.get i : Perm α) = -1)

/-- Check the base witness and all conditions of the requested claim. -/
def certificateCheck (gs : List (Perm α))
    (c : DecodedCertificate (FiniteAction.ambientGroup gs)) : Bool :=
  baseCheck gs c && claimCheck c

theorem certificateCheck_iff (gs : List (Perm α))
    (c : DecodedCertificate (FiniteAction.ambientGroup gs)) :
    certificateCheck gs c = true ↔ Valid c := by
  simp only [certificateCheck, Bool.and_eq_true, baseCheck_iff, Valid]
  apply and_congr_right
  intro _
  cases hc : c.claim <;>
    simp [claimCheck, hc, cycleValidCheck_iff,
      List.forall_mem_iff_get, List.exists_mem_iff_get]

/-- A decoded certificate carrying a proof that its finite checks are valid. -/
structure VerifiedCertificate (gs : List (Perm α)) where
  /-- The certificate interpreted in the subgroup generated by the supplied input. -/
  certificate : DecodedCertificate (FiniteAction.ambientGroup gs)
  valid : Valid certificate

/-- Return a valid certificate or reject it after executing the finite checks. -/
def validate (gs : List (Perm α)) (c : DecodedCertificate (FiniteAction.ambientGroup gs)) :
    Option (VerifiedCertificate gs) :=
  if h : certificateCheck gs c = true then
    some ⟨c, (certificateCheck_iff gs c).mp h⟩
  else none

theorem validate_isSome_iff (gs : List (Perm α))
    (c : DecodedCertificate (FiniteAction.ambientGroup gs)) :
    (validate gs c).isSome = true ↔ Valid c := by
  simp [validate, certificateCheck_iff]

theorem VerifiedCertificate.sound (gs : List (Perm α)) (result : VerifiedCertificate gs) :
    ClaimHolds result.certificate :=
  certificate_sound _ result.valid

theorem checker_sound (gs : List (Perm α))
    (c : DecodedCertificate (FiniteAction.ambientGroup gs))
    (h : certificateCheck gs c = true) :
    ClaimHolds c :=
  certificate_sound c ((certificateCheck_iff gs c).mp h)


end TauCeti.CertifiedPermutation
