/-
Copyright (c) 2026 Vincent Quenneville-Belair. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vincent Quenneville-Belair
-/
module

public import TauCeti.GroupTheory.Perm.Certificates.StrongJordan

/-!
# Soundness of the decoded classical permutation-group certificate

These definitions describe the mathematical data after successful decoding.
They do not implement a raw-input parser or claim a machine running-time bound.
-/

open MulAction SubMulAction Subgroup Equiv Equiv.Perm

@[expose] public section

namespace TauCeti.CertifiedPermutation

variable {α : Type*} [Fintype α] [DecidableEq α]
variable {P : Subgroup (Perm α)}

/-- A word in the listed subgroup generators and their inverses. -/
abbrev SignedWord (hs : List P) := List (Fin hs.length × Bool)

/-- The subgroup generated by the entries of a generator list. -/
def generated (hs : List P) : Subgroup P :=
  closure {h | h ∈ hs}

/-- Evaluate a signed subgroup word with the rightmost factor acting first. -/
def signedWordEval (hs : List P) (word : SignedWord hs) : P :=
  (word.map fun letter =>
    if letter.2 then (hs.get letter.1)⁻¹ else hs.get letter.1).prod

omit [Fintype α] [DecidableEq α] in
theorem signedWordEval_mem (hs : List P) (word : SignedWord hs) :
    signedWordEval hs word ∈ generated hs := by
  induction word with
  | nil => exact (generated hs).one_mem
  | cons letter word ih =>
    change (if letter.2 then (hs.get letter.1)⁻¹ else hs.get letter.1) *
      signedWordEval hs word ∈ generated hs
    have hmem : hs.get letter.1 ∈ generated hs :=
      subset_closure (hs.get_mem letter.1)
    apply (generated hs).mul_mem _ ih
    split <;> first | exact (generated hs).inv_mem hmem | exact hmem

omit [Fintype α] [DecidableEq α] in
theorem generated_le_fixing (hs : List P) (s : Set α)
    (hfix : ∀ h ∈ hs, ∀ x ∈ s, (h : Perm α) x = x) :
    generated hs ≤ fixingSubgroup P s := by
  rw [generated, closure_le]
  intro h hh
  exact (mem_fixingSubgroup_iff P).mpr (hfix h hh)

theorem generated_le_even (hs : List P)
    (heven : ∀ h ∈ hs, sign (h : Perm α) = 1) :
    generated hs ≤ (alternatingGroup α).comap P.subtype := by
  rw [generated, closure_le]
  intro h hh
  exact mem_alternatingGroup.mpr (heven h hh)

/-- An ambient conjugator and a signed subgroup generator for a normal-closure factor. -/
structure ConjugateFactor (hs : List P) where
  /-- The element of the ambient group used to conjugate the generator. -/
  conjugator : P
  /-- The position of the generator in `hs`. -/
  generatorIndex : Fin hs.length
  /-- Whether to use the inverse of the selected generator. -/
  inverted : Bool

/-- Evaluate one conjugate of a signed subgroup generator. -/
def factorEval (hs : List P) (factor : ConjugateFactor hs) : P :=
  factor.conjugator *
    (if factor.inverted then (hs.get factor.generatorIndex)⁻¹
      else hs.get factor.generatorIndex) *
    factor.conjugator⁻¹

/-- Evaluate a finite product of conjugated signed subgroup generators. -/
def conjugateProduct (hs : List P) (factors : List (ConjugateFactor hs)) : P :=
  (factors.map (factorEval hs)).prod

omit [Fintype α] [DecidableEq α] in
theorem factorEval_mem_normalClosure (hs : List P) (factor : ConjugateFactor hs) :
    factorEval hs factor ∈ normalClosure (generated hs : Set P) := by
  have hmem : hs.get factor.generatorIndex ∈ normalClosure (generated hs : Set P) :=
    le_normalClosure (subset_closure (hs.get_mem factor.generatorIndex))
  apply normalClosure_normal.conj_mem
  split <;> first | exact inv_mem hmem | exact hmem

omit [Fintype α] [DecidableEq α] in
theorem conjugateProduct_mem_normalClosure
    (hs : List P) (factors : List (ConjugateFactor hs)) :
    conjugateProduct hs factors ∈ normalClosure (generated hs : Set P) := by
  induction factors with
  | nil => exact one_mem _
  | cons factor factors ih =>
    exact mul_mem (factorEval_mem_normalClosure hs factor) ih

/-- The supported normal-closure claims: double transitivity, alternating, or symmetric. -/
inductive Claim where
  | doublyTransitive
  | alternating
  | symmetric

/-- A fixing-set, orbit, and optional prime-cycle witness over a permutation subgroup. -/
structure DecodedCertificate (P : Subgroup (Perm α)) where
  /-- The property asserted of the normal closure. -/
  claim : Claim
  /-- The subgroup generators, interpreted as elements of the ambient group. -/
  generators : List P
  /-- The nonempty set that each subgroup generator fixes pointwise. -/
  fixedSet : Finset α
  /-- The starting point for the orbit witnesses, outside `fixedSet`. -/
  base : α
  /-- For each point outside `fixedSet`, a word taking `base` to that point. -/
  orbitWords : α → SignedWord generators
  /-- A product in the normal closure used for the prime-cycle check, when required. -/
  cycleFactors : List (ConjugateFactor generators)

/-- The ambient permutation image of the normal closure of listed subgroup generators. -/
def closureImage (hs : List P) : Subgroup (Perm α) :=
  (normalClosure (generated hs : Set P)).map P.subtype

/-- The permutation denoted by the certificate’s product of conjugate factors. -/
def cycleValue (certificate : DecodedCertificate P) : Perm α :=
  conjugateProduct certificate.generators certificate.cycleFactors

/-- The primitive-action, fixing-set, cardinality, and orbit witness hypotheses. -/
structure BaseValid (certificate : DecodedCertificate P) : Prop where
  primitive : IsPreprimitive P α
  fixedNonempty : certificate.fixedSet.Nonempty
  cardinality : certificate.fixedSet.card + 1 < Nat.card α
  baseOutside : certificate.base ∉ certificate.fixedSet
  fixes : ∀ h ∈ certificate.generators, ∀ x ∈ certificate.fixedSet,
    (h : Perm α) x = x
  reaches : ∀ x ∉ certificate.fixedSet,
    (signedWordEval certificate.generators (certificate.orbitWords x) : Perm α)
      certificate.base = x

/-- A prime-cycle witness satisfying the support bound in Jordan’s theorem. -/
def CycleValid (certificate : DecodedCertificate P) : Prop :=
  (cycleValue certificate).IsCycle ∧
    (cycleValue certificate).support.card.Prime ∧
    (cycleValue certificate).support.card + 3 ≤ Nat.card α

/-- The base witness and the cycle and parity requirements of the requested claim. -/
def Valid (certificate : DecodedCertificate P) : Prop :=
  BaseValid certificate ∧
    match certificate.claim with
    | .doublyTransitive => True
    | .alternating => CycleValid certificate ∧
        ∀ h ∈ certificate.generators, sign (h : Perm α) = 1
    | .symmetric => CycleValid certificate ∧
        ∃ h ∈ certificate.generators, sign (h : Perm α) = -1

/-- The mathematical claim made about the certificate’s normal-closure image. -/
def ClaimHolds (certificate : DecodedCertificate P) : Prop :=
  match certificate.claim with
  | .doublyTransitive =>
      IsMultiplyPretransitive (closureImage certificate.generators) α 2
  | .alternating =>
      closureImage certificate.generators = alternatingGroup α
  | .symmetric =>
      closureImage certificate.generators = ⊤

omit [Fintype α] [DecidableEq α] in
theorem complement_transitive (certificate : DecodedCertificate P)
    (hvalid : BaseValid certificate) :
    ∀ x y : α, x ∉ (certificate.fixedSet : Set α) →
      y ∉ (certificate.fixedSet : Set α) →
      ∃ h : generated certificate.generators, (h : P) • x = y := by
  intro x y hx hy
  let u : generated certificate.generators :=
    ⟨signedWordEval certificate.generators (certificate.orbitWords x),
      signedWordEval_mem _ _⟩
  let v : generated certificate.generators :=
    ⟨signedWordEval certificate.generators (certificate.orbitWords y),
      signedWordEval_mem _ _⟩
  have hu : (u : P) • certificate.base = x := hvalid.reaches x hx
  have hv : (v : P) • certificate.base = y := hvalid.reaches y hy
  refine ⟨v * u⁻¹, ?_⟩
  rw [Subgroup.coe_mul, Subgroup.coe_inv, mul_smul, ← hu, inv_smul_smul]
  exact hv

omit [Fintype α] [DecidableEq α] in
theorem closureImage_doublyTransitive (certificate : DecodedCertificate P)
    (hvalid : BaseValid certificate) :
    IsMultiplyPretransitive (closureImage certificate.generators) α 2 := by
  have hpos : 0 < certificate.fixedSet.card := Finset.card_pos.mpr hvalid.fixedNonempty
  have hsn : (certificate.fixedSet : Set α).ncard =
      (certificate.fixedSet.card - 1) + 1 := by
    rw [Set.ncard_coe_finset]
    omega
  have hcard : (certificate.fixedSet.card - 1) + 2 < Nat.card α := by
    have := hvalid.cardinality
    omega
  have hN := TauCeti.normalClosure_is_two_pretransitive_of_witnesses
    hvalid.primitive hsn hcard
    (generated_le_fixing _ _ hvalid.fixes) (complement_transitive certificate hvalid)
  rw [is_two_pretransitive_iff] at hN ⊢
  intro a b c d hab hcd
  obtain ⟨u, hu, hv⟩ := hN hab hcd
  refine ⟨⟨(u : P), mem_map_of_mem P.subtype u.prop⟩, hu, hv⟩

theorem alternating_le_closureImage (certificate : DecodedCertificate P)
    (hvalid : BaseValid certificate) (hcycle : CycleValid certificate) :
    alternatingGroup α ≤ closureImage certificate.generators := by
  exact TauCeti.alternatingGroup_le_of_isPreprimitive_of_isCycle_mem
    (isPreprimitive_of_is_two_pretransitive
      (closureImage_doublyTransitive certificate hvalid))
    hcycle.2.1 hcycle.2.2 hcycle.1 rfl
    (mem_map_of_mem P.subtype (conjugateProduct_mem_normalClosure _ _))

/-- Every valid decoded certificate proves its stated classical group claim. -/
theorem certificate_sound (certificate : DecodedCertificate P)
    (hvalid : Valid certificate) : ClaimHolds certificate := by
  obtain ⟨hbase, hclaim⟩ := hvalid
  unfold ClaimHolds
  cases htag : certificate.claim with
  | doublyTransitive =>
    exact closureImage_doublyTransitive certificate hbase
  | alternating =>
    have heven := (show CycleValid certificate ∧
      (∀ h ∈ certificate.generators, sign (h : Perm α) = 1) from
      by simpa [htag] using hclaim)
    exact le_antisymm
      (TauCeti.normalClosure_image_le_alternatingGroup
        (generated_le_even _ heven.2))
      (alternating_le_closureImage certificate hbase heven.1)
  | symmetric =>
    have hodd := (show CycleValid certificate ∧
      (∃ h ∈ certificate.generators, sign (h : Perm α) = -1) from
      by simpa [htag] using hclaim)
    obtain ⟨h, hh, hsign⟩ := hodd.2
    exact TauCeti.eq_top_of_alternatingGroup_le_of_odd
      (alternating_le_closureImage certificate hbase hodd.1)
      (mem_map_of_mem P.subtype (le_normalClosure (subset_closure hh))) hsign


end TauCeti.CertifiedPermutation
