/-
Copyright (c) 2026 Vincent Quenneville-Belair. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vincent Quenneville-Belair
-/
module

public import TauCeti.GroupTheory.Perm.Certificates.Tables

/-!
# Uniform machines for finite permutation actions

Point sets are Boolean lists and relations are Boolean matrices. The degree is
part of the input. A sweep has a bounded output size; the unary clocks for orbit
and relation saturation have lengths `n` and `n * n`, respectively.
-/

@[expose] public section

namespace TauCeti.PermutationTables

open Equiv Computability BitEncoding Turing

/-- A point set represented by membership bits in point order. -/
abbrev PointSet := List Bool
/-- A binary point relation represented by rows of membership bits. -/
abbrev Relation := List PointSet

/-- Look up a membership bit, treating points beyond the list as absent. -/
def member (s : PointSet) (x : ℕ) : Bool := s[x]?.getD false

/-- Look up a relation bit, treating missing rows or columns as false. -/
def related (r : Relation) (x y : ℕ) : Bool := member (r[x]?.getD []) y

/-- Extend a point set by generator and inverse-generator images. -/
def orbitStep (n : ℕ) (gs : List Table) (s : PointSet) : PointSet :=
  (List.range n).map fun x =>
    member s x ||
      gs.any (fun g => member s (lookup n (inv n g) x)) ||
      gs.any (fun g => member s (lookup n g x))

/-- Compute the orbit of `a` by `n` bounded closure steps. -/
def orbit (n : ℕ) (gs : List Table) (a : ℕ) : PointSet :=
  (orbitStep n gs)^[n] ((List.range n).map fun x => decide (x = a))

/-- Check that the bounded orbit contains every point. -/
def transitive (n : ℕ) (gs : List Table) (a : ℕ) : Bool :=
  (orbit n gs a).all id

/-- Extend a relation by equivalence closure and simultaneous generator images. -/
def relationStep (n : ℕ) (gs : List Table) (r : Relation) : Relation :=
  (List.range n).map fun x => (List.range n).map fun y =>
    related r x y || decide (x = y) || related r y x ||
      (List.range n).any (fun z => related r x z && related r z y) ||
      gs.any (fun g => related r (lookup n (inv n g) x) (lookup n (inv n g) y)) ||
      gs.any (fun g => related r (lookup n g x) (lookup n g y))

/-- Compute the invariant equivalence relation generated by `(a, b)` in `n * n` steps. -/
def relation (n : ℕ) (gs : List Table) (a b : ℕ) : Relation :=
  (relationStep n gs)^[n * n]
    ((List.range n).map fun x =>
      (List.range n).map fun y => decide (x = a) && decide (y = b))

/-- Check transitivity and universality of every nontrivial generated point relation. -/
def primitive (n : ℕ) (gs : List Table) (a : ℕ) : Bool :=
  transitive n gs a &&
    (List.range n).all (fun b => decide (a = b) || (relation n gs a b).all (·.all id))

@[fun_prop] theorem polyTime_member :
    PolyTime (fun p : PointSet × ℕ => member p.1 p.2) := by
  unfold member
  fun_prop

@[fun_prop] theorem polyTime_related :
    PolyTime (fun p : Relation × ℕ × ℕ => related p.1 p.2.1 p.2.2) := by
  unfold related
  fun_prop

@[fun_prop] theorem polyTime_orbitStep :
    PolyTime (fun p : (ℕ × List Table) × PointSet => orbitStep p.1.1 p.1.2 p.2) := by
  unfold orbitStep
  fun_prop

theorem length_enc_orbitStep (n : ℕ) (gs : List Table) (s : PointSet) :
    (enc (orbitStep n gs s)).length ≤ (n + 2) ^ 3 := by
  rw [length_enc_bits]
  simp only [orbitStep, List.length_map, List.length_range]
  nlinarith [Nat.zero_le (n ^ 3), Nat.zero_le (n ^ 2)]

@[fun_prop] theorem polyTime_orbit :
    PolyTime (fun p : (ℕ × List Table) × ℕ => orbit p.1.1 p.1.2 p.2) := by
  have hi := PolyTime.iterate₂
    (g := fun p : ℕ × List Table => orbitStep p.1 p.2) polyTime_orbitStep 3 fun p s => by
    have h := length_enc_orbitStep p.1 p.2 s
    have hn : p.1 ≤ (enc p).length := by rw [length_enc_prod, length_enc_nat]; omega
    have hp := Nat.pow_le_pow_left (by omega : p.1 + 2 ≤ (enc p).length + 2) 3
    omega
  exact PolyTime.comp (f := fun p : (ℕ × List Table) × ℕ =>
    (p.1, p.1.1, (List.range p.1.1).map fun x => decide (x = p.2))) hi (by fun_prop)

@[fun_prop] theorem polyTime_transitive :
    PolyTime (fun p : (ℕ × List Table) × ℕ => transitive p.1.1 p.1.2 p.2) := by
  unfold transitive
  fun_prop

@[fun_prop] theorem polyTime_relationStep :
    PolyTime (fun p : (ℕ × List Table) × Relation => relationStep p.1.1 p.1.2 p.2) := by
  unfold relationStep
  fun_prop

theorem length_enc_relationStep (n : ℕ) (gs : List Table) (r : Relation) :
    (enc (relationStep n gs r)).length ≤ (n + 2) ^ 4 := by
  have h := length_enc_list_le (relationStep n gs r) (B := 4 * n + 1) (by
    intro row hrow
    obtain ⟨x, _, rfl⟩ := List.mem_map.mp hrow
    simp [length_enc_bits])
  rw [show (relationStep n gs r).length = n by simp [relationStep]] at h
  nlinarith [Nat.zero_le (n ^ 4), Nat.zero_le (n ^ 3)]

@[fun_prop] theorem polyTime_relation :
    PolyTime (fun p : (ℕ × List Table) × ℕ × ℕ => relation p.1.1 p.1.2 p.2.1 p.2.2) := by
  have hi := PolyTime.iterate₂
    (g := fun p : ℕ × List Table => relationStep p.1 p.2) polyTime_relationStep 4 fun p r => by
    have h := length_enc_relationStep p.1 p.2 r
    have hn : p.1 ≤ (enc p).length := by rw [length_enc_prod, length_enc_nat]; omega
    have hp := Nat.pow_le_pow_left (by omega : p.1 + 2 ≤ (enc p).length + 2) 4
    omega
  exact PolyTime.comp (f := fun p : (ℕ × List Table) × ℕ × ℕ =>
    (p.1, p.1.1 * p.1.1, (List.range p.1.1).map fun x =>
      (List.range p.1.1).map fun y => decide (x = p.2.1) && decide (y = p.2.2)))
    hi (by fun_prop)

@[fun_prop] theorem polyTime_primitive :
    PolyTime (fun p : (ℕ × List Table) × ℕ => primitive p.1.1 p.1.2 p.2) := by
  have hb : PolyTime (fun s : PointSet => s.all id) :=
    PolyTime.all (f := fun _ b => b) PolyTime.snd PolyTime.id
  have hr : PolyTime (fun r : Relation => r.all (·.all id)) :=
    PolyTime.all (f := fun _ (s : PointSet) => s.all id)
      (PolyTime.comp hb PolyTime.snd) PolyTime.id
  have hw : PolyTime (fun p : ((ℕ × List Table) × ℕ) × ℕ =>
      relation p.1.1.1 p.1.1.2 p.1.2 p.2) :=
    PolyTime.comp (f := fun p : ((ℕ × List Table) × ℕ) × ℕ =>
      (p.1.1, p.1.2, p.2)) polyTime_relation (by fun_prop)
  have hf : PolyTime (fun p : ((ℕ × List Table) × ℕ) × ℕ =>
      decide (p.1.2 = p.2) || (relation p.1.1.1 p.1.1.2 p.1.2 p.2).all (·.all id)) :=
    PolyTime.comp PolyTime.or (PolyTime.pair (by fun_prop) (PolyTime.comp hr hw))
  have hall := PolyTime.all
    (f := fun p b => decide (p.2 = b) || (relation p.1.1 p.1.2 p.2 b).all (·.all id)) hf
    (show PolyTime (fun p : (ℕ × List Table) × ℕ => List.range p.1.1) by fun_prop)
  exact PolyTime.comp PolyTime.and (PolyTime.pair polyTime_transitive hall)

/-- The canonical Boolean vector of a finite point set. -/
def setBits {n : ℕ} (s : Finset (Fin n)) : PointSet :=
  List.ofFn fun x => decide (x ∈ s)

/-- The canonical Boolean matrix of a finite relation. -/
def relationBits {n : ℕ} (r : Finset (Fin n × Fin n)) : Relation :=
  List.ofFn fun x => List.ofFn fun y => decide ((x, y) ∈ r)

@[simp] theorem member_ofFn {n : ℕ} (f : Fin n → Bool) (x : Fin n) :
    member (List.ofFn f) x.val = f x := by
  simp [member, x.isLt]

@[simp] theorem member_setBits {n : ℕ} (s : Finset (Fin n)) (x : Fin n) :
    member (setBits s) x.val = decide (x ∈ s) := member_ofFn _ _

@[simp] theorem related_relationBits {n : ℕ} (r : Finset (Fin n × Fin n)) (x y : Fin n) :
    related (relationBits r) x.val y.val = decide ((x, y) ∈ r) := by
  simp [related, relationBits, x.isLt]

theorem any_get {α : Type*} (l : List α) (f : α → Bool) :
    l.any f = true ↔ ∃ i : Fin l.length, f (l.get i) = true := by
  rw [List.any_eq_true]
  constructor
  · rintro ⟨x, hx, hf⟩
    obtain ⟨i, rfl⟩ := List.mem_iff_get.mp hx
    exact ⟨i, hf⟩
  · rintro ⟨i, hi⟩
    exact ⟨l.get i, l.get_mem i, hi⟩

theorem all_range (n : ℕ) (f : ℕ → Bool) :
    (List.range n).all f = true ↔ ∀ x : Fin n, f x.val = true := by
  simp only [List.all_eq_true, List.mem_range]
  constructor
  · intro h x; exact h x.val x.isLt
  · intro h x hx; exact h ⟨x, hx⟩

theorem any_range (n : ℕ) (f : ℕ → Bool) :
    (List.range n).any f = true ↔ ∃ x : Fin n, f x.val = true := by
  simp only [List.any_eq_true, List.mem_range]
  constructor
  · rintro ⟨x, hx, hf⟩; exact ⟨⟨x, hx⟩, hf⟩
  · rintro ⟨x, hx⟩; exact ⟨x.val, x.isLt, hx⟩

theorem any_ofFn {α : Type*} {n : ℕ} (f : Fin n → α) (p : α → Bool) :
    (List.ofFn f).any p = true ↔ ∃ x : Fin n, p (f x) = true := by
  simp [List.any_eq_true, List.mem_ofFn]

theorem orbitStep_setBits {n : ℕ} (gs : List (Perm (Fin n))) (s : Finset (Fin n)) :
    orbitStep n (gs.map ofPerm) (setBits s) = setBits (FiniteAction.orbitStep gs s) := by
  rw [orbitStep, range_eq_ofFn, List.map_ofFn]
  congr 1
  funext x
  apply Bool.eq_iff_iff.mpr
  simp only [Function.comp_apply, Bool.or_eq_true, List.any_map, any_get, inv_ofPerm,
    lookup_ofPerm, member_setBits, decide_eq_true_eq, FiniteAction.mem_orbitStep]
  tauto

theorem relationStep_relationBits {n : ℕ} (gs : List (Perm (Fin n)))
    (r : Finset (Fin n × Fin n)) :
    relationStep n (gs.map ofPerm) (relationBits r) =
      relationBits (FiniteAction.relationStep gs r) := by
  rw [relationStep, range_eq_ofFn, List.map_ofFn]
  congr 1
  funext x
  simp only [Function.comp_apply, List.map_ofFn]
  congr 1
  funext y
  apply Bool.eq_iff_iff.mpr
  simp only [Function.comp_apply, Bool.or_eq_true, Bool.and_eq_true, List.any_map, any_ofFn]
  simp only [any_get, Function.comp_apply, inv_ofPerm, lookup_ofPerm, related_relationBits,
    decide_eq_true_eq, FiniteAction.mem_relationStep, Fin.ext_iff]
  simp only [or_assoc]

theorem saturate_eq_iterate {α : Type*} [DecidableEq α]
    (f : Finset α → Finset α) (N : ℕ) (s : Finset α) :
    FiniteClosure.saturate f N s = f^[N] s := by
  induction N generalizing s with
  | zero => rfl
  | succ N ih =>
    by_cases h : f s = s
    · simp [FiniteClosure.saturate, h, Function.iterate_fixed h]
    · simp only [FiniteClosure.saturate, h, ite_false, ih, Function.iterate_succ_apply]

theorem orbit_ofPerm {n : ℕ} (gs : List (Perm (Fin n))) (a : Fin n) :
    orbit n (gs.map ofPerm) a.val = setBits (FiniteAction.orbit gs a) := by
  have hi : ∀ N s, (orbitStep n (gs.map ofPerm))^[N] (setBits s) =
      setBits ((FiniteAction.orbitStep gs)^[N] s) := by
    intro N s
    induction N with
    | zero => rfl
    | succ N ih => rw [Function.iterate_succ_apply', ih, orbitStep_setBits,
        Function.iterate_succ_apply']
  have hseed : (List.range n).map (fun x => decide (x = a.val)) =
      setBits {a} := by
    rw [range_eq_ofFn, List.map_ofFn]
    congr 1
    funext x
    simp [Function.comp_apply, Fin.ext_iff]
  rw [orbit, hseed, hi, FiniteAction.orbit, Fintype.card_fin, saturate_eq_iterate]

theorem relation_ofPerm {n : ℕ} (gs : List (Perm (Fin n))) (a b : Fin n) :
    relation n (gs.map ofPerm) a.val b.val = relationBits (FiniteAction.relation gs a b) := by
  have hi : ∀ N r, (relationStep n (gs.map ofPerm))^[N] (relationBits r) =
      relationBits ((FiniteAction.relationStep gs)^[N] r) := by
    intro N r
    induction N with
    | zero => rfl
    | succ N ih => rw [Function.iterate_succ_apply', ih, relationStep_relationBits,
        Function.iterate_succ_apply']
  have hseed : (List.range n).map (fun x => (List.range n).map
      (fun y => decide (x = a.val) && decide (y = b.val))) = relationBits {(a, b)} := by
    rw [range_eq_ofFn, List.map_ofFn]
    congr 1
    funext x
    simp only [Function.comp_apply, List.map_ofFn]
    congr 1
    funext y
    simp [Function.comp_apply, Fin.ext_iff]
  rw [relation, hseed, hi, FiniteAction.relation, Fintype.card_prod,
    Fintype.card_fin, saturate_eq_iterate]

theorem all_setBits {n : ℕ} (s : Finset (Fin n)) :
    (setBits s).all id = true ↔ s = Finset.univ := by
  simp [setBits, List.all_eq_true, List.mem_ofFn, Finset.eq_univ_iff_forall]

theorem all_relationBits {n : ℕ} (r : Finset (Fin n × Fin n)) :
    (relationBits r).all (·.all id) = true ↔ r = Finset.univ := by
  simp [relationBits, List.all_eq_true, List.mem_ofFn, Finset.eq_univ_iff_forall,
    Prod.forall]

theorem transitive_ofPerm {n : ℕ} (gs : List (Perm (Fin n))) (a : Fin n) :
    transitive n (gs.map ofPerm) a.val = FiniteAction.transitiveCheck gs a := by
  apply Bool.eq_iff_iff.mpr
  rw [transitive, orbit_ofPerm, all_setBits]
  simp [FiniteAction.transitiveCheck]

theorem primitive_ofPerm {n : ℕ} (gs : List (Perm (Fin n))) (a : Fin n) :
    primitive n (gs.map ofPerm) a.val = FiniteAction.primitiveCheck gs a := by
  apply Bool.eq_iff_iff.mpr
  simp only [primitive, transitive_ofPerm, Bool.and_eq_true, all_range,
    Bool.or_eq_true, decide_eq_true_eq, relation_ofPerm, all_relationBits]
  simp [FiniteAction.primitiveCheck, Fin.ext_iff, or_iff_not_imp_left]

end TauCeti.PermutationTables
