/-
Copyright (c) 2026 Vincent Quenneville-Belair. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Vincent Quenneville-Belair
-/
module

public import TauCeti.Data.Finset.Saturation
public import Mathlib.GroupTheory.GroupAction.Primitive
public import Mathlib.GroupTheory.GroupAction.Transitive
public import Mathlib.GroupTheory.Perm.Basic

/-!
# Executable orbit and primitivity checks

The algorithms traverse points, pairs of points, and generator indices.
They never enumerate the generated group or the subsets of the point set.
Orbit saturation uses at most `card α` sweeps; equivalence-relation
saturation uses at most `card (α × α)` sweeps.
-/

open Equiv MulAction Subgroup
open scoped Pointwise

@[expose] public section

namespace TauCeti.FiniteAction

variable {α : Type*} [Fintype α] [DecidableEq α]

/-- The permutation subgroup generated by the entries of a list. -/
def ambientGroup (gs : List (Perm α)) : Subgroup (Perm α) :=
  closure {g | g ∈ gs}

/-- A listed permutation regarded as an element of its generated subgroup. -/
def generator (gs : List (Perm α)) (i : Fin gs.length) : ambientGroup gs :=
  ⟨gs.get i, subset_closure (gs.get_mem i)⟩

/-- Add images and inverse images of the current points under every listed generator. -/
def orbitStep (gs : List (Perm α)) (s : Finset α) : Finset α :=
  Finset.univ.filter fun x =>
    x ∈ s ∨ (∃ i : Fin gs.length, (gs.get i)⁻¹ x ∈ s) ∨
      ∃ i : Fin gs.length, gs.get i x ∈ s

@[simp]
theorem mem_orbitStep (gs : List (Perm α)) (s : Finset α) (x : α) :
    x ∈ orbitStep gs s ↔
      x ∈ s ∨ (∃ i : Fin gs.length, (gs.get i)⁻¹ x ∈ s) ∨
        ∃ i : Fin gs.length, gs.get i x ∈ s := by
  simp [orbitStep]

theorem subset_orbitStep (gs : List (Perm α)) (s : Finset α) :
    s ⊆ orbitStep gs s := fun _ hx => (mem_orbitStep _ _ _).mpr (.inl hx)

/-- Compute a point’s orbit by at most the number of points many saturation sweeps. -/
def orbit (gs : List (Perm α)) (a : α) : Finset α :=
  FiniteClosure.saturate (orbitStep gs) (Fintype.card α) {a}

theorem orbit_fixed (gs : List (Perm α)) (a : α) :
    orbitStep gs (orbit gs a) = orbit gs a :=
  FiniteClosure.saturate_card_fixed _ (subset_orbitStep gs) _

theorem self_mem_orbit (gs : List (Perm α)) (a : α) : a ∈ orbit gs a :=
  FiniteClosure.subset_saturate _ (subset_orbitStep gs) _ _ (by simp)

/-- Permutations preserving membership in a finite point set. -/
def setStabilizer (s : Finset α) : Subgroup (Perm α) where
  carrier := {g | ∀ x, x ∈ s ↔ g x ∈ s}
  one_mem' := by simp
  mul_mem' := by
    intro g h hg hh x
    exact (hh x).trans (hg (h x))
  inv_mem' := by
    intro g hg x
    simpa using (hg (g⁻¹ x)).symm

theorem ambient_le_orbitStabilizer (gs : List (Perm α)) (a : α) :
    ambientGroup gs ≤ setStabilizer (orbit gs a) := by
  rw [ambientGroup, closure_le]
  intro g hg
  obtain ⟨i, rfl⟩ := List.mem_iff_get.mp hg
  intro x
  constructor
  · intro hx
    rw [← orbit_fixed gs a]
    exact (mem_orbitStep _ _ _).mpr (.inr (.inl ⟨i, by simpa using hx⟩))
  · intro hx
    rw [← orbit_fixed gs a]
    exact (mem_orbitStep _ _ _).mpr (.inr (.inr ⟨i, hx⟩))

theorem orbitStep_witness (gs : List (Perm α)) (a : α) (s : Finset α)
    (hs : ∀ x ∈ s, ∃ g : ambientGroup gs, (g : Perm α) a = x) :
    ∀ x ∈ orbitStep gs s, ∃ g : ambientGroup gs, (g : Perm α) a = x := by
  intro x hx
  rcases (mem_orbitStep _ _ _).mp hx with hx | ⟨i, hi⟩ | ⟨i, hi⟩
  · exact hs x hx
  · obtain ⟨g, hg⟩ := hs _ hi
    refine ⟨generator gs i * g, ?_⟩
    simp [generator, Perm.mul_apply, hg]
  · obtain ⟨g, hg⟩ := hs _ hi
    refine ⟨(generator gs i)⁻¹ * g, ?_⟩
    simp [generator, Perm.mul_apply, hg]

theorem mem_orbit_iff (gs : List (Perm α)) (a x : α) :
    x ∈ orbit gs a ↔ ∃ g : ambientGroup gs, (g : Perm α) a = x := by
  constructor
  · exact FiniteClosure.saturate_preserves (orbitStep gs) (Fintype.card α)
      (fun s => ∀ x ∈ s, ∃ g : ambientGroup gs, (g : Perm α) a = x)
      (orbitStep_witness gs a) (by
        intro x hx
        simp only [Finset.mem_singleton] at hx
        subst x
        exact ⟨1, rfl⟩) x
  · rintro ⟨g, rfl⟩
    exact (ambient_le_orbitStabilizer gs a g.prop a).mp (self_mem_orbit gs a)

/-- Check whether the base point’s computed orbit contains every point. -/
def transitiveCheck (gs : List (Perm α)) (a : α) : Bool :=
  decide (orbit gs a = Finset.univ)

theorem transitiveCheck_iff (gs : List (Perm α)) (a : α) :
    transitiveCheck gs a = true ↔ IsPretransitive (ambientGroup gs) α := by
  simp only [transitiveCheck, decide_eq_true_eq]
  rw [isPretransitive_iff_base a]
  constructor
  · intro h x
    exact (mem_orbit_iff gs a x).mp (by simp [h])
  · intro h
    apply Finset.eq_univ_iff_forall.mpr
    intro x
    exact (mem_orbit_iff gs a x).mpr (h x)

/-- Add reflexivity, symmetry, transitivity, and generator invariance to a finite relation. -/
def relationStep (gs : List (Perm α)) (r : Finset (α × α)) : Finset (α × α) :=
  Finset.univ.filter fun xy =>
    xy ∈ r ∨ xy.1 = xy.2 ∨ (xy.2, xy.1) ∈ r ∨
      (∃ z, (xy.1, z) ∈ r ∧ (z, xy.2) ∈ r) ∨
      (∃ i : Fin gs.length, ((gs.get i)⁻¹ xy.1, (gs.get i)⁻¹ xy.2) ∈ r) ∨
      ∃ i : Fin gs.length, (gs.get i xy.1, gs.get i xy.2) ∈ r

@[simp]
theorem mem_relationStep (gs : List (Perm α)) (r : Finset (α × α)) (x y : α) :
    (x, y) ∈ relationStep gs r ↔
      (x, y) ∈ r ∨ x = y ∨ (y, x) ∈ r ∨
        (∃ z, (x, z) ∈ r ∧ (z, y) ∈ r) ∨
        (∃ i : Fin gs.length, ((gs.get i)⁻¹ x, (gs.get i)⁻¹ y) ∈ r) ∨
        ∃ i : Fin gs.length, (gs.get i x, gs.get i y) ∈ r := by
  simp [relationStep]

theorem subset_relationStep (gs : List (Perm α)) (r : Finset (α × α)) :
    r ⊆ relationStep gs r := by
  rintro ⟨x, y⟩ hxy
  exact (mem_relationStep _ _ _ _).mpr (.inl hxy)

/-- Saturate a pair to the least generator-invariant equivalence relation containing it. -/
def relation (gs : List (Perm α)) (a b : α) : Finset (α × α) :=
  FiniteClosure.saturate (relationStep gs) (Fintype.card (α × α)) {(a, b)}

theorem relation_fixed (gs : List (Perm α)) (a b : α) :
    relationStep gs (relation gs a b) = relation gs a b :=
  FiniteClosure.saturate_card_fixed _ (subset_relationStep gs) _

theorem pair_mem_relation (gs : List (Perm α)) (a b : α) :
    (a, b) ∈ relation gs a b :=
  FiniteClosure.subset_saturate _ (subset_relationStep gs) _ _ (by simp)

theorem relation_equivalence (gs : List (Perm α)) (a b : α) :
    Equivalence (fun x y => (x, y) ∈ relation gs a b) := by
  refine ⟨?_, ?_, ?_⟩
  · intro x
    rw [← relation_fixed gs a b]
    exact (mem_relationStep _ _ _ _).mpr (.inr (.inl rfl))
  · intro x y hxy
    rw [← relation_fixed gs a b]
    exact (mem_relationStep _ _ _ _).mpr (.inr (.inr (.inl hxy)))
  · intro x y z hxy hyz
    rw [← relation_fixed gs a b]
    exact (mem_relationStep _ _ _ _).mpr (.inr (.inr (.inr (.inl ⟨y, hxy, hyz⟩))))

/-- Permutations preserving a finite relation on ordered pairs of points. -/
def relationStabilizer (r : Finset (α × α)) : Subgroup (Perm α) where
  carrier := {g | ∀ x y, (x, y) ∈ r ↔ (g x, g y) ∈ r}
  one_mem' := by simp
  mul_mem' := by
    intro g h hg hh x y
    exact (hh x y).trans (hg (h x) (h y))
  inv_mem' := by
    intro g hg x y
    simpa using (hg (g⁻¹ x) (g⁻¹ y)).symm

theorem ambient_le_relationStabilizer (gs : List (Perm α)) (a b : α) :
    ambientGroup gs ≤ relationStabilizer (relation gs a b) := by
  rw [ambientGroup, closure_le]
  intro g hg
  obtain ⟨i, rfl⟩ := List.mem_iff_get.mp hg
  intro x y
  constructor
  · intro hxy
    rw [← relation_fixed gs a b]
    exact (mem_relationStep _ _ _ _).mpr
      (.inr (.inr (.inr (.inr (.inl ⟨i, by simpa using hxy⟩)))))
  · intro hxy
    rw [← relation_fixed gs a b]
    exact (mem_relationStep _ _ _ _).mpr
      (.inr (.inr (.inr (.inr (.inr ⟨i, hxy⟩)))))

/-- Saturation is the least generator-invariant equivalence relation
containing the specified pair. -/
theorem relation_le (gs : List (Perm α)) (a b : α) (R : α → α → Prop)
    (hR : Equivalence R)
    (hgens : ∀ i : Fin gs.length, ∀ x y, R x y ↔ R (gs.get i x) (gs.get i y))
    (hab : R a b) :
    ∀ x y, (x, y) ∈ relation gs a b → R x y := by
  have hstep : ∀ r : Finset (α × α),
      (∀ x y, (x, y) ∈ r → R x y) →
      ∀ x y, (x, y) ∈ relationStep gs r → R x y := by
    intro r hr x y hxy
    rcases (mem_relationStep _ _ _ _).mp hxy with
      hxy | hxy | hxy | ⟨z, hxz, hzy⟩ | ⟨i, hi⟩ | ⟨i, hi⟩
    · exact hr _ _ hxy
    · subst y
      exact hR.refl _
    · exact hR.symm (hr _ _ hxy)
    · exact hR.trans (hr _ _ hxz) (hr _ _ hzy)
    · simpa using (hgens i _ _).mp (hr _ _ hi)
    · exact (hgens i _ _).mpr (hr _ _ hi)
  exact FiniteClosure.saturate_preserves (relationStep gs) (Fintype.card (α × α))
    (fun r => ∀ x y, (x, y) ∈ r → R x y) hstep (by
      intro x y hxy
      simp only [Finset.mem_singleton, Prod.mk.injEq] at hxy
      rcases hxy with ⟨rfl, rfl⟩
      exact hab)

theorem relation_class_isBlock (gs : List (Perm α)) (a b : α) :
    IsBlock (ambientGroup gs) {x | (a, x) ∈ relation gs a b} := by
  let R := fun x y => (x, y) ∈ relation gs a b
  have he := relation_equivalence gs a b
  have hi (g : ambientGroup gs) (x y : α) :
      R x y ↔ R (g • x) (g • y) :=
    ambient_le_relationStabilizer gs a b g.prop x y
  rw [isBlock_iff_smul_eq_of_mem]
  intro g x hx hgx
  have hga : R a (g • a) :=
    he.trans hgx (he.symm ((hi g a x).mp hx))
  ext z
  rw [Set.mem_smul_set_iff_inv_smul_mem]
  change R a (g⁻¹ • z) ↔ R a z
  constructor
  · intro hz
    have hgz : R (g • a) z := by simpa using (hi g a (g⁻¹ • z)).mp hz
    exact he.trans hga hgz
  · intro hz
    apply (hi g a (g⁻¹ • z)).mpr
    simpa using he.trans (he.symm hga) hz

theorem relation_eq_univ_of_primitive (gs : List (Perm α)) (a b : α)
    (hprim : IsPreprimitive (ambientGroup gs) α) (hab : a ≠ b) :
    relation gs a b = Finset.univ := by
  let := hprim
  have he := relation_equivalence gs a b
  have hb := pair_mem_relation gs a b
  have hblock := relation_class_isBlock gs a b
  rcases IsPreprimitive.isTrivialBlock_of_isBlock hblock with hsingle | hall
  · exact (hab (hsingle (he.refl a) hb)).elim
  · apply Finset.eq_univ_iff_forall.mpr
    rintro ⟨x, y⟩
    have hx : (a, x) ∈ relation gs a b := by
      change x ∈ {x | (a, x) ∈ relation gs a b}
      rw [hall]
      trivial
    have hy : (a, y) ∈ relation gs a b := by
      change y ∈ {x | (a, x) ∈ relation gs a b}
      rw [hall]
      trivial
    exact he.trans (he.symm hx) hy

private def blockRelation (gs : List (Perm α)) (B : Set α) (x y : α) : Prop :=
  ∀ g : ambientGroup gs, x ∈ g • B ↔ y ∈ g • B

omit [Fintype α] [DecidableEq α] in
private theorem blockRelation_equivalence (gs : List (Perm α)) (B : Set α) :
    Equivalence (blockRelation gs B) :=
  ⟨fun _ _ => Iff.rfl, fun h g => (h g).symm, fun h₁ h₂ g => (h₁ g).trans (h₂ g)⟩

omit [Fintype α] [DecidableEq α] in
private theorem blockRelation_generator (gs : List (Perm α)) (B : Set α)
    (i : Fin gs.length) (x y : α) :
    blockRelation gs B x y ↔ blockRelation gs B (gs.get i x) (gs.get i y) := by
  let g := generator gs i
  change (∀ h : ambientGroup gs, x ∈ h • B ↔ y ∈ h • B) ↔
    (∀ h : ambientGroup gs, g • x ∈ h • B ↔ g • y ∈ h • B)
  constructor
  · intro hr h
    simpa [Set.mem_smul_set_iff_inv_smul_mem, mul_smul] using hr (g⁻¹ * h)
  · intro hr h
    simpa [Set.mem_smul_set_iff_inv_smul_mem, mul_smul] using hr (g * h)

omit [Fintype α] [DecidableEq α] in
private theorem blockRelation_of_mem (gs : List (Perm α)) (B : Set α)
    (hB : IsBlock (ambientGroup gs) B) {a b : α} (ha : a ∈ B) (hb : b ∈ B) :
    blockRelation gs B a b := by
  intro g
  constructor
  · intro hag
    have heq : g • B = B := hB.smul_eq_of_nonempty ⟨a, hag, ha⟩
    simpa [heq] using hb
  · intro hbg
    have heq : g • B = B := hB.smul_eq_of_nonempty ⟨b, hbg, hb⟩
    simpa [heq] using ha

theorem primitive_of_relations_eq_univ (gs : List (Perm α)) (a : α)
    (htrans : IsPretransitive (ambientGroup gs) α)
    (hall : ∀ b, a ≠ b → relation gs a b = Finset.univ) :
    IsPreprimitive (ambientGroup gs) α := by
  let := htrans
  apply IsPreprimitive.of_isTrivialBlock_base a
  intro B ha hB
  by_cases hsingle : B.Subsingleton
  · exact .inl hsingle
  · right
    have hb : ∃ b ∈ B, a ≠ b := by
      by_contra hn
      push Not at hn
      apply hsingle
      intro x hx y hy
      exact (hn x hx).symm.trans (hn y hy)
    obtain ⟨b, hb, hab⟩ := hb
    apply Set.eq_univ_of_forall
    intro x
    have hr := relation_le gs a b (blockRelation gs B)
      (blockRelation_equivalence gs B) (blockRelation_generator gs B)
      (blockRelation_of_mem gs B hB ha hb) a x (by simp [hall b hab])
    simpa using (hr 1).mp (by simpa using ha)

/-- Check transitivity and universal pair-generated invariant equivalence relations. -/
def primitiveCheck (gs : List (Perm α)) (a : α) : Bool :=
  transitiveCheck gs a && decide (∀ b, a ≠ b → relation gs a b = Finset.univ)

/-- The finite saturation algorithm decides Mathlib's primitivity predicate. -/
theorem primitiveCheck_iff (gs : List (Perm α)) (a : α) :
    primitiveCheck gs a = true ↔ IsPreprimitive (ambientGroup gs) α := by
  simp only [primitiveCheck, Bool.and_eq_true, decide_eq_true_eq, transitiveCheck_iff]
  constructor
  · rintro ⟨htrans, hall⟩
    exact primitive_of_relations_eq_univ gs a htrans hall
  · intro hprim
    exact ⟨hprim.toIsPretransitive, fun b hab =>
      relation_eq_univ_of_primitive gs a b hprim hab⟩


end TauCeti.FiniteAction
